---
- name: Setup mysql
  hosts: db
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - mysql-client
    - name: Allow hosts to connect
      shell: sed -i "s/.*bind-address.*/bind-address = 0.0.0.0/" /etc/mysql/mariadb.conf.d/50-server.cnf
    - name: Start mysql
      service:
        name: mysqld
        state: restarted
    - name: Create database
      mysql_db:
        name: guestbook
        state: present
    - name: Create database users
      mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present
        host: '%'

- name: Setup guestbook application
  hosts: web
  vars:
    db_user: "db_user"
    db_password: "Passw0rd"
    db_name: "guestbook"
    db_host: "35.239.103.48"
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: "present"
      loop:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - python-pip
        - python-mysqldb
    - name: Install flask
      pip:
        name: "{{ item }}"
      loop:
        - configparser
        - Flask
        - Flask-sqlalchemy
    - name: Download guestbook source code
      git:
        repo: https://github.com/ameade/flask-guestbook
        dest: /opt/flask-guestbook
    - name: Check if application is running
      shell: "ps -ef |grep -v grep | grep -w flask |awk '{print $2}'"
      register: process_id
      changed_when: process_id.stdout != ""
    - name: Stop the application
      shell: "kill {{ process_id.stdout }}"
      when: process_id.stdout != ""
    - name: Create guestbook config directory
      file:
        path: "/opt/guestbook"
        state: directory
    - name: Configure application
      template:
        src: "vars.ini.j2"
        dest: "/opt/guestbook/vars.ini"
    - name: Start the application
      shell: FLASK_APP=/opt/flask-guestbook/app.py nohup flask run -h 0.0.0.0 -p 8080 &
